name: skill_helper_new
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge/
  - defaults
dependencies:
  - kivy=1.11.1
  - numpy=1.19.0
  - pandas=1.0.5
  - pip=20.1.1
  - pyinstaller=3.6
  - python=3.8.2
  - python-dateutil=2.8.1
  - pyyaml=5.3.1
  - setuptools=49.2.0
