#:import group_screen group_screen
<GroupScreen>:
    name: "group_screen"
    stats: _stats
    BoxLayout:
        orientation: 'vertical'
        GroupView:
            id: _group_view
            screen_manager: root.manager
            groups: root.manager.database.groups
        SkillControlGroupPanel:
            screen_manager: root.manager
            size_hint: 1, 0.1
        Label:
            size_hint: 1, 0.05
            id: _stats